name: 'Test'

on:
  push:
    branches:
      - typescript

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: typescript

      - uses: ./
        id: diawi
        with:
          token: ${{ secrets.DIAWI_TOKEN }}
          file: ./example.apk
          comment: 'Uploaded from Github Action'

      - name: Output
        run: echo "Diawi URL = ${{ steps.diawi.outputs['url'] }}"
